name: Gatling Tests

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run Gatling tests - Simulation 0
        run: mvn gatling:test -Dgatling.simulationClass=socialcarepassport.CreateNotificationSimulation

      - name: Run Gatling tests - Simulation 1
        run: mvn gatling:test -Dgatling.simulationClass=socialcarepassport.GetBookedCoursesSimulation

      - name: Run Gatling tests - Simulation 2
        run: mvn gatling:test -Dgatling.simulationClass=socialcarepassport.GetDownloadTrainingRecordSimulation

      - name: Run Gatling tests - Simulation 3
        run: mvn gatling:test -Dgatling.simulationClass=socialcarepassport.GetEmployerListSimulation

      - name: Run Gatling tests - Simulation 4
        run: mvn gatling:test -Dgatling.simulationClass=socialcarepassport.GetNotificationsByCurrentUser

      - name: Run Gatling tests - Simulation 5
        run: mvn gatling:test -Dgatling.simulationClass=socialcarepassport.PostCreateUserSimulation

      - name: Archive Gatling Reports
        uses: actions/upload-artifact@v2
        with:
          name: gatling-reports
          path: target/gatling/*/index.html
          retention-days: 5